name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins job
        run: |
          curl -X POST \
            --user "admin:${{ secrets.JENKINS_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/test-pipeline-v2/build" \
            -H "ngrok-skip-browser-warning: true"